spring:
  application:
    name: vehicle.service
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle-service-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
springdoc:
  swagger-ui:
    path: /swagger-ui
logging:
  level:
    org.springframework.boot.flyway: INFO
